name: counter
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: null
  formz: null
  flutter_bloc: null

  rainwater_theme:
    path: ../packages/rainwater_theme

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Regular.ttf
        - asset: fonts/Manrope-Bold.ttf
          weight: 700